// pipeline {
//     agent any

//     stages {
//         stage('Install Dependencies') {
//             steps {
//                 bat 'npm install'
//             }
//         }

//         stage('Install Playwright Browsers') {
//             steps {
//                 bat 'npx playwright install'
//             }
//         }

//         stage('Run Tests') {
//             steps {
//                 bat 'npx playwright test'
//             }
//         }
//     }
// } 
pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('Project') {
                    bat 'npm install'
                }
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                dir('Project') {
                    bat 'npx playwright install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Project') {
                    bat 'npx playwright test'
                }
            }
        }
    }
} 


